export interface Environment {
  production: boolean,
  NAME: string,
  froalaKey: string,
  googleAuthKey: string,
  backUrl: string,
  backUrlImage: string,
  staticPagesUrl: string,
  SEGMENT_API_KEY: string,
  SEGMENT_DEBUG: boolean,
  FACEBOOK_APP_ID: string,
  DEFAULT_FICTION_ID: string,
  DEFAULT_NON_FICTION_ID: string,
  APPCUSE_ID: string,
};
